[package]
name = "rotools"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Helpful stuff."
homepage = "https://ronanmccabe.app/"
repository = "https://github.com/ronanyeah/rotools"
keywords = ["ronan"]
categories = ["web-programming"]

[dependencies]
graphql_client = "0.10.0"
reqwest = { version = "0.11.5", features = ["json"] }
serde = "1.0.130"
serde_json = "1.0.68"
url = "2.2.2"
